// ─── THE HEALING COVENANT MAP ─────────────────────────────────────────────────
// All cross-references vetted against Treasury of Scripture Knowledge (TSK)
// and Nave's Topical Bible. Every node traces to the Cross within 2 hops.
// Red letter = direct speech of Jesus only.
//
// Categories: faith | healing | prayer | covenant | word | jesus

export const MAP_META = {
  id: "healingCovenant",
  title: "The Healing Covenant",
  subtitle: "Faith, Healing & the Promises of God",
  anchor: "Isaiah 53:5",
  verseCount: 45,
  description:
    "Every healing promise flows from the finished work of the Cross. Jehovah Rapha — the Lord your Healer — is not a title He earned; it is His name. These scriptures map the covenant of health that was purchased for every believer at Calvary.",
  journey: [
    { nodeId: "f1",    note: "Faith is the foundation — it is the substance of what God promised" },
    { nodeId: "f2",    note: "Faith grows by hearing the Word — it cannot be manufactured" },
    { nodeId: "w1",    note: "The Word itself is medicine: 'health to all your flesh'" },
    { nodeId: "h1",    note: "The root of every healing promise: by His stripes you were healed" },
    { nodeId: "h9",    note: "Peter confirms it in the new covenant — the price was paid" },
    { nodeId: "h7",    note: "Jehovah Rapha — healing is not what He does, it is His name" },
    { nodeId: "c1",    note: "The covenant was established before the sickness — it supersedes it" },
    { nodeId: "c2",    note: "Christ redeemed us from the curse — we stand in covenant health" },
    { nodeId: "p1",    note: "Bring nothing anxiously — bring everything by prayer and supplication" },
    { nodeId: "h4",    note: "The prayer of faith shall save the sick — this is the covenant in action" },
    { nodeId: "j1",    note: "Jesus was anointed to heal — it was His explicit assignment" },
    { nodeId: "j3",    note: "Life more abundantly — healing is part of the fullness He came to give" },
    { nodeId: "cross", note: "It is finished — every promise was sealed here at the cost of His blood" },
  ],
};

// Cross-reference sources:
//  TSK  = Treasury of Scripture Knowledge
//  NAV  = Nave's Topical Bible
//  SB   = Standard study Bible marginals (ESV, NIV, NASB)

export const NODES = [
  // ── FAITH ────────────────────────────────────────────────────────────────────
  {
    id: "f1", category: "faith", redLetter: false,
    ref: "Hebrews 11:1",
    textKJV: "Now faith is the substance of things hoped for, the evidence of things not seen.",
    textESV: "Now faith is the assurance of things hoped for, the conviction of things not seen.",
    textNKJV: "Now faith is the substance of things hoped for, the evidence of things not seen.",
    application: "Faith is not a feeling — it is a settled conviction that God's Word is more real than any symptom. When the diagnosis contradicts the promise, faith chooses the promise.",
    source: "TSK: cross-refs Heb 10:22, Rom 8:25, 2 Cor 4:18",
    connections: ["f2", "f3", "f5", "h1", "c1"],
    position: { x: 15, y: 18 },
  },
  {
    id: "f2", category: "faith", redLetter: false,
    ref: "Romans 10:17",
    textKJV: "So then faith cometh by hearing, and hearing by the word of God.",
    textESV: "So faith comes from hearing, and hearing through the word of Christ.",
    textNKJV: "So then faith comes by hearing, and hearing by the word of God.",
    application: "Faith is cultivated, not conjured. Hearing the Word — especially aloud — is how faith grows. Read healing promises over yourself daily.",
    source: "TSK: cross-refs Isa 55:3, John 5:24, Gal 3:2",
    connections: ["f1", "f4", "w1", "w2", "h1"],
    position: { x: 8, y: 32 },
  },
  {
    id: "f3", category: "faith", redLetter: true,
    ref: "Mark 11:24",
    textKJV: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.",
    textESV: "Therefore I tell you, whatever you ask in prayer, believe that you have received it, and it will be yours.",
    textNKJV: "Therefore I say to you, whatever things you ask when you pray, believe that you receive them, and you will have them.",
    application: "Jesus taught present-tense faith: believe you have received before you see it. This is agreeing with what God has already declared done at the Cross.",
    source: "TSK: cross-refs Matt 21:22, Luke 11:9, John 14:13",
    connections: ["f1", "f4", "f6", "h3", "p1", "p3"],
    position: { x: 8, y: 50 },
  },
  {
    id: "f4", category: "faith", redLetter: false,
    ref: "James 1:6",
    textKJV: "But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed.",
    textESV: "But let him ask in faith, with no doubting, for the one who doubts is like a wave of the sea that is driven and tossed by the wind.",
    textNKJV: "But let him ask in faith, with no doubting, for he who doubts is like a wave of the sea driven and tossed by the wind.",
    application: "Doubt is not a feeling — it is an unstable posture. Fix your anchor on what God said. The Word does not shift the way circumstances do.",
    source: "TSK: cross-refs Heb 10:23, Matt 21:21, Mark 9:24",
    connections: ["f2", "f3", "f7", "h4", "p2"],
    position: { x: 14, y: 67 },
  },
  {
    id: "f5", category: "faith", redLetter: true,
    ref: "Matthew 17:20",
    textKJV: "If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you.",
    textESV: "For truly, I say to you, if you have faith like a grain of mustard seed, you will say to this mountain, 'Move from here to there,' and it will move, and nothing will be impossible for you.",
    textNKJV: "So Jesus said to them, 'For assuredly, I say to you, if you have faith as a mustard seed, you will say to this mountain, Move from here to there, and it will move; and nothing will be impossible for you.'",
    application: "Faith doesn't need to be large — it needs to be genuine and directed. Speak to the mountain of sickness with authority rooted in Christ's finished work.",
    source: "TSK: cross-refs Luke 17:6, Mark 9:23, 1 Cor 13:2",
    connections: ["f1", "f3", "h2", "h6", "j2"],
    position: { x: 24, y: 80 },
  },
  {
    id: "f6", category: "faith", redLetter: false,
    ref: "Ephesians 6:16",
    textKJV: "Above all, taking the shield of faith, wherewith ye shall be able to quench all the fiery darts of the wicked.",
    textESV: "In all circumstances take up the shield of faith, with which you can extinguish all the flaming darts of the evil one.",
    textNKJV: "Above all, taking the shield of faith with which you will be able to quench all the fiery darts of the wicked one.",
    application: "Faith is active armor. Every accusation — 'What if you don't recover?' — is met by raising the shield: 'It is written...'",
    source: "TSK: cross-refs 1 Thess 5:8, 1 Pet 5:9, Rom 13:12",
    connections: ["f3", "f4", "f7", "h5", "p4"],
    position: { x: 10, y: 20 },
  },
  {
    id: "f7", category: "faith", redLetter: false,
    ref: "2 Corinthians 5:7",
    textKJV: "For we walk by faith, not by sight.",
    textESV: "For we walk by faith, not by sight.",
    textNKJV: "For we walk by faith, not by sight.",
    application: "Walking by faith means your daily decisions align with the Word, not with what symptoms say. What you act on reveals what you truly believe.",
    source: "TSK: cross-refs Heb 11:1, Rom 8:24, 1 Pet 1:8",
    connections: ["f1", "f6", "w2", "h6"],
    position: { x: 20, y: 40 },
  },
  {
    id: "f8", category: "faith", redLetter: false,
    ref: "Hebrews 11:6",
    textKJV: "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.",
    textESV: "And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him.",
    textNKJV: "But without faith it is impossible to please Him, for he who comes to God must believe that He is, and that He is a rewarder of those who diligently seek Him.",
    application: "Faith is not optional. It is the very currency of our relationship with God. Coming to Him with expectation is itself an act of faith He rewards.",
    source: "TSK: cross-refs Rom 14:23, John 4:48, Heb 10:38",
    connections: ["f1", "f2", "p1", "c1", "cross"],
    position: { x: 22, y: 58 },
  },
  {
    id: "f9", category: "faith", redLetter: true,
    ref: "John 14:12",
    textKJV: "Verily, verily, I say unto you, He that believeth on me, the works that I do shall he do also; and greater works than these shall he do; because I go unto my Father.",
    textESV: "Truly, truly, I say to you, whoever believes in me will also do the works that I do; and greater works than these will he do, because I am going to the Father.",
    textNKJV: "Most assuredly, I say to you, he who believes in Me, the works that I do he will do also; and greater works than these he will do, because I go to My Father.",
    application: "Jesus included healing in 'the works that I do.' The believer's authority to pray for healing flows directly from this promise — not from personal merit, but from the indwelling Spirit.",
    source: "TSK: cross-refs Mark 16:17, Luke 10:17, Acts 3:6",
    connections: ["f1", "j1", "j3", "h3", "cross"],
    position: { x: 30, y: 25 },
  },
  {
    id: "f10", category: "faith", redLetter: false,
    ref: "Romans 4:20-21",
    textKJV: "He staggered not at the promise of God through unbelief; but was strong in faith, giving glory to God; and being fully persuaded that, what he had promised, he was able also to perform.",
    textESV: "No unbelief made him waver concerning the promise of God, but he grew strong in his faith as he gave glory to God, fully convinced that God was able to do what he had promised.",
    textNKJV: "He did not waver at the promise of God through unbelief, but was strengthened in faith, giving glory to God, and being fully convinced that what He had promised He was also able to perform.",
    application: "Abraham's model: he looked at his body and then looked at God's Word — and chose the Word. This is the pattern of healing faith. The circumstances are real; God's promise is more real.",
    source: "TSK: cross-refs Gen 17:17, Heb 11:12, Rom 8:24",
    connections: ["f1", "f8", "c1", "c2", "cross"],
    position: { x: 32, y: 45 },
  },

  // ── HEALING ───────────────────────────────────────────────────────────────────
  {
    id: "h1", category: "healing", redLetter: false,
    ref: "Isaiah 53:5",
    textKJV: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
    textESV: "But he was pierced for our transgressions; he was crushed for our iniquities; upon him was the chastisement that brought us peace, and with his wounds we are healed.",
    textNKJV: "But He was wounded for our transgressions, He was bruised for our iniquities; the chastisement for our peace was upon Him, and by His stripes we are healed.",
    application: "Healing is past tense: 'we ARE healed.' This was written 700 years before the Cross — and fulfilled at it. We do not beg for what Christ already secured; we receive it by faith.",
    source: "TSK: cross-refs 1 Pet 2:24, Matt 8:17, Mark 15:15",
    connections: ["f1", "f2", "h3", "h7", "j1", "c2", "cross"],
    position: { x: 85, y: 18 },
  },
  {
    id: "h2", category: "healing", redLetter: false,
    ref: "Psalm 103:2-3",
    textKJV: "Bless the LORD, O my soul, and forget not all his benefits: who forgiveth all thine iniquities; who healeth all thy diseases.",
    textESV: "Bless the LORD, O my soul, and forget not all his benefits, who forgives all your iniquity, who heals all your diseases.",
    textNKJV: "Bless the Lord, O my soul, and forget not all His benefits: Who forgives all your iniquities, Who heals all your diseases.",
    application: "Healing is listed as a covenant benefit right alongside forgiveness. If you believe God forgives sins, you have the same scriptural ground to believe He heals diseases — same verse, same promise.",
    source: "TSK: cross-refs Exod 15:26, Deut 7:15, Ps 107:20",
    connections: ["f1", "f5", "h1", "h7", "c1", "c2"],
    position: { x: 92, y: 32 },
  },
  {
    id: "h3", category: "healing", redLetter: false,
    ref: "Matthew 8:16-17",
    textKJV: "He cast out the spirits with his word, and healed all that were sick: that it might be fulfilled which was spoken by Esaias the prophet, saying, Himself took our infirmities, and bare our sicknesses.",
    textESV: "He cast out the spirits with a word and healed all who were sick. This was to fulfill what was spoken by the prophet Isaiah: 'He took our illnesses and bore our diseases.'",
    textNKJV: "When evening had come, they brought to Him many who were demon-possessed. And He cast out the spirits with a word, and healed all who were sick, that it might be fulfilled which was spoken by Isaiah the prophet, saying: 'He Himself took our infirmities and bore our sicknesses.'",
    application: "Jesus healed ALL who came — not most, not some. Matthew quotes Isaiah 53:4 to say this was the fulfillment of the promise. His ministry was the covenant made visible.",
    source: "TSK: cross-refs Luke 4:40, Isa 53:4, Acts 10:38",
    connections: ["h1", "h4", "f3", "j1", "j3", "cross"],
    position: { x: 92, y: 50 },
  },
  {
    id: "h4", category: "healing", redLetter: false,
    ref: "James 5:14-15",
    textKJV: "Is any sick among you? let him call for the elders of the church; and let them pray over him, anointing him with oil in the name of the Lord: and the prayer of faith shall save the sick.",
    textESV: "Is anyone among you sick? Let him call for the elders of the church, and let them pray over him, anointing him with oil in the name of the Lord. And the prayer of faith will save the one who is sick.",
    textNKJV: "Is anyone among you sick? Let him call for the elders of the church, and let them pray over him, anointing him with oil in the name of the Lord. And the prayer of faith will save the sick, and the Lord will raise him up.",
    application: "God designed healing to happen in community — the body of Christ praying together. Healing is not a solo project. Let others stand with you in faith.",
    source: "TSK: cross-refs Mark 6:13, Acts 9:17, 1 Cor 11:30",
    connections: ["f4", "h3", "h5", "p2", "p4"],
    position: { x: 86, y: 68 },
  },
  {
    id: "h5", category: "healing", redLetter: false,
    ref: "Jeremiah 17:14",
    textKJV: "Heal me, O LORD, and I shall be healed; save me, and I shall be saved: for thou art my praise.",
    textESV: "Heal me, O LORD, and I shall be healed; save me, and I shall be saved, for you are my praise.",
    textNKJV: "Heal me, O Lord, and I shall be healed; save me, and I shall be saved, for You are my praise.",
    application: "This is a declaration of certainty, not desperate pleading. Jeremiah speaks the outcome before it arrives. Pray this way: 'Lord, heal me — and I shall be healed.'",
    source: "TSK: cross-refs Isa 38:16, Jer 30:17, Ps 6:2",
    connections: ["f1", "f6", "h4", "p1", "c1"],
    position: { x: 74, y: 80 },
  },
  {
    id: "h6", category: "healing", redLetter: false,
    ref: "3 John 1:2",
    textKJV: "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.",
    textESV: "Beloved, I pray that all may go well with you and that you may be in good health, as it goes well with your soul.",
    textNKJV: "Beloved, I pray that you may prosper in all things and be in health, just as your soul prospers.",
    application: "God's desire is wholeness — body, soul, and spirit together. As your inner life deepens in the Word, your expectation of physical health should rise with it.",
    source: "TSK: cross-refs Ps 73:24, Isa 58:11, 1 Thess 5:23",
    connections: ["f5", "f7", "h2", "h1"],
    position: { x: 89, y: 20 },
  },
  {
    id: "h7", category: "healing", redLetter: false,
    ref: "Exodus 15:26",
    textKJV: "For I am the LORD that healeth thee.",
    textESV: "For I am the LORD, your healer.",
    textNKJV: "For I am the Lord who heals you.",
    application: "Jehovah Rapha — this is one of God's seven covenant names. Healing is not just something He does; it is woven into who He is. You are praying to the God whose name is Healer.",
    source: "TSK: cross-refs Deut 32:39, Hos 6:1, Ps 30:2",
    connections: ["h1", "h2", "h8", "c1", "c2", "cross"],
    position: { x: 78, y: 36 },
  },
  {
    id: "h8", category: "healing", redLetter: false,
    ref: "Acts 10:38",
    textKJV: "How God anointed Jesus of Nazareth with the Holy Ghost and with power: who went about doing good, and healing all that were oppressed of the devil; for God was with him.",
    textESV: "God anointed Jesus of Nazareth with the Holy Spirit and with power. He went about doing good and healing all who were oppressed by the devil, for God was with him.",
    textNKJV: "How God anointed Jesus of Nazareth with the Holy Spirit and with power, who went about doing good and healing all who were oppressed by the devil, for God was with Him.",
    application: "Sickness is described here as oppression by the enemy — not God's design. Jesus came to undo it. The same Holy Spirit who anointed Him lives in every believer.",
    source: "TSK: cross-refs Luke 4:18, John 3:2, 1 John 3:8",
    connections: ["h3", "h7", "j1", "j3", "f6"],
    position: { x: 80, y: 57 },
  },
  {
    id: "h9", category: "healing", redLetter: false,
    ref: "1 Peter 2:24",
    textKJV: "Who his own self bare our sins in his own body on the tree, that we, being dead to sins, should live unto righteousness: by whose stripes ye were healed.",
    textESV: "He himself bore our sins in his body on the tree, that we might die to sin and live to righteousness. By his wounds you have been healed.",
    textNKJV: "Who Himself bore our sins in His own body on the tree, that we, having died to sins, might live for righteousness — by whose stripes you were healed.",
    application: "Peter quotes Isaiah 53:5 in the past tense: 'you WERE healed.' He wrote this decades after the Cross to believers who were suffering. The healing was already accomplished.",
    source: "TSK: cross-refs Isa 53:5, Col 1:22, Heb 9:28",
    connections: ["h1", "h3", "c2", "cross"],
    position: { x: 76, y: 52 },
  },
  {
    id: "h10", category: "healing", redLetter: false,
    ref: "Psalm 107:20",
    textKJV: "He sent his word, and healed them, and delivered them from their destructions.",
    textESV: "He sent out his word and healed them, and delivered them from their destruction.",
    textNKJV: "He sent His word and healed them, and delivered them from their destructions.",
    application: "God's Word is the instrument of healing — not just comfort, not just instruction. The same Word that created the world is the Word that heals. Speak it over yourself.",
    source: "TSK: cross-refs Matt 8:8, John 4:50, Ps 30:2",
    connections: ["w1", "w2", "h1", "f2", "j1"],
    position: { x: 68, y: 82 },
  },
  {
    id: "h11", category: "healing", redLetter: false,
    ref: "Mark 16:17-18",
    textKJV: "And these signs shall follow them that believe... they shall lay hands on the sick, and they shall recover.",
    textESV: "And these signs will accompany those who believe... they will lay their hands on the sick, and they will recover.",
    textNKJV: "And these signs will follow those who believe... they will lay hands on the sick, and they will recover.",
    application: "Healing through the laying on of hands is described as a sign that follows believers — not just apostles, not just a select few. This is the commission of the whole church.",
    source: "TSK: cross-refs Luke 10:17, Acts 8:7, James 5:14",
    connections: ["h3", "h4", "j3", "f9", "cross"],
    position: { x: 72, y: 70 },
  },
  {
    id: "h12", category: "healing", redLetter: false,
    ref: "Isaiah 58:8",
    textKJV: "Then shall thy light break forth as the morning, and thine health shall spring forth speedily.",
    textESV: "Then shall your light break forth like the dawn, and your healing shall spring up speedily.",
    textNKJV: "Then your light shall break forth like the morning, your healing shall spring forth speedily.",
    application: "Healing is described as something that springs — not trickles. God's healing is abundant, not reluctant. Come to Him expecting light, not dim hope.",
    source: "TSK: cross-refs Isa 57:18, Jer 30:17, Mal 4:2",
    connections: ["h1", "h5", "c1", "w2"],
    position: { x: 84, y: 82 },
  },

  // ── PRAYER ────────────────────────────────────────────────────────────────────
  {
    id: "p1", category: "prayer", redLetter: false,
    ref: "Philippians 4:6",
    textKJV: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",
    textESV: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.",
    textNKJV: "Be anxious for nothing, but in everything by prayer and supplication, with thanksgiving, let your requests be made known to God.",
    application: "Thanksgiving is the posture that opens the door. Before your healing manifests, thank God for it — this is faith expressed as gratitude, not denial of your circumstance.",
    source: "TSK: cross-refs 1 Thess 5:17, Col 4:2, Matt 6:25",
    connections: ["f3", "f8", "h5", "p2", "p3"],
    position: { x: 36, y: 88 },
  },
  {
    id: "p2", category: "prayer", redLetter: false,
    ref: "1 John 5:14-15",
    textKJV: "And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us: and if we know that he hear us, whatsoever we ask, we know that we have the petitions that we desired of him.",
    textESV: "And this is the confidence that we have toward him, that if we ask anything according to his will he hears us. And if we know that he hears us in whatever we ask, we know that we have the requests that we have asked of him.",
    textNKJV: "Now this is the confidence that we have in Him, that if we ask anything according to His will, He hears us. And if we know that He hears us, whatever we ask, we know that we have the petitions that we have asked of Him.",
    application: "Healing IS His will — Psalm 103, Isaiah 53, Exodus 15:26 establish this. So you are not praying in uncertainty when you pray for healing; you are praying in confidence.",
    source: "TSK: cross-refs Matt 7:7, John 15:7, Jer 29:12",
    connections: ["f4", "h4", "p1", "p3", "c2"],
    position: { x: 46, y: 93 },
  },
  {
    id: "p3", category: "prayer", redLetter: true,
    ref: "Matthew 21:22",
    textKJV: "And all things, whatsoever ye shall ask in prayer, believing, ye shall receive.",
    textESV: "And whatever you ask in prayer, you will receive, if you have faith.",
    textNKJV: "And whatever things you ask in prayer, believing, you will receive.",
    application: "The condition is faith, not worthiness. You don't earn healing by being good enough — you receive it because Christ was good enough, and you believe Him.",
    source: "TSK: cross-refs Mark 11:24, John 15:7, Luke 11:9",
    connections: ["f3", "f8", "p1", "p4", "cross"],
    position: { x: 29, y: 74 },
  },
  {
    id: "p4", category: "prayer", redLetter: false,
    ref: "Romans 8:26",
    textKJV: "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered.",
    textESV: "Likewise the Spirit helps us in our weakness. For we do not know what to pray for as we ought, but the Spirit himself intercedes for us with groanings too deep for words.",
    textNKJV: "Likewise the Spirit also helps in our weaknesses. For we do not know what we should pray for as we ought, but the Spirit Himself makes intercession for us with groanings which cannot be uttered.",
    application: "When you don't know how to pray, the Holy Spirit prays through you. You are never left without intercession. Your weakness becomes a doorway for God's strength.",
    source: "TSK: cross-refs Zech 12:10, Eph 6:18, Jude 1:20",
    connections: ["f6", "h4", "p2", "p3", "j3"],
    position: { x: 37, y: 74 },
  },
  {
    id: "p5", category: "prayer", redLetter: true,
    ref: "John 16:23-24",
    textKJV: "And in that day ye shall ask me nothing. Verily, verily, I say unto you, Whatsoever ye shall ask the Father in my name, he will give it you. Hitherto have ye asked nothing in my name: ask, and ye shall receive, that your joy may be full.",
    textESV: "In that day you will ask nothing of me. Truly, truly, I say to you, whatever you ask of the Father in my name, he will give it to you. Until now you have asked nothing in my name. Ask, and you will receive, that your joy may be full.",
    textNKJV: "And in that day you will ask Me nothing. Most assuredly, I say to you, whatever you ask the Father in My name He will give you. Until now you have asked nothing in My name. Ask, and you will receive, that your joy may be full.",
    application: "The name of Jesus is not a formula — it is an identity. Praying in His name means coming on the basis of His person, His merit, and His covenant. It is the access code to the Father that Christ gave you.",
    source: "TSK: cross-refs John 14:13, Matt 18:19, Acts 3:6",
    connections: ["p1", "p2", "p3", "j1", "cross"],
    position: { x: 28, y: 88 },
  },
  {
    id: "p6", category: "prayer", redLetter: false,
    ref: "Matthew 18:19-20",
    textKJV: "Again I say unto you, That if two of you shall agree on earth as touching any thing that they shall ask, it shall be done for them of my Father which is in heaven. For where two or three are gathered together in my name, there am I in the midst of them.",
    textESV: "Again I say to you, if two of you agree on earth about anything they ask, it will be done for them by my Father in heaven. For where two or three are gathered in my name, there am I among them.",
    textNKJV: "Again I say to you that if two of you agree on earth concerning anything that they ask, it will be done for them by My Father in heaven. For where two or three are gathered together in My name, I am there in the midst of them.",
    application: "Corporate agreement in prayer carries divine weight. Two believers in agreement about healing, in the name of Jesus, access the Father's promise. Bring others into agreement with you.",
    source: "TSK: cross-refs John 15:7, 1 John 5:14, Acts 1:14",
    connections: ["p1", "p4", "p5", "h4"],
    position: { x: 20, y: 82 },
  },
  {
    id: "p7", category: "prayer", redLetter: false,
    ref: "Isaiah 65:24",
    textKJV: "And it shall come to pass, that before they call, I will answer; and while they are yet speaking, I will hear.",
    textESV: "Before they call I will answer; while they are yet speaking I will hear.",
    textNKJV: "It shall come to pass that before they call, I will answer; and while they are still speaking, I will hear.",
    application: "God's response is not slow. His answer can precede your asking. Healing can begin before the prayer is finished. He is already present and already moving.",
    source: "TSK: cross-refs Ps 145:18, Dan 9:21, Isa 58:9",
    connections: ["p1", "p2", "h5", "c1"],
    position: { x: 46, y: 80 },
  },

  // ── COVENANT ──────────────────────────────────────────────────────────────────
  {
    id: "c1", category: "covenant", redLetter: false,
    ref: "Deuteronomy 7:15",
    textKJV: "And the LORD will take away from thee all sickness, and will put none of the evil diseases of Egypt, which thou knowest, upon thee.",
    textESV: "And the LORD will take away from you all sickness, and none of the evil diseases of Egypt, which you knew, will he inflict on you.",
    textNKJV: "And the Lord will take away from you all sickness, and will afflict you with none of the terrible diseases of Egypt which you have known.",
    application: "This was God's covenant promise to Israel — and through Christ, you are grafted into that covenant (Romans 11:17). Sickness was never part of God's inheritance for His people.",
    source: "TSK: cross-refs Exod 15:26, Deut 28:60, Gal 3:13",
    connections: ["h2", "h7", "h5", "c2", "f8", "p7"],
    position: { x: 38, y: 10 },
  },
  {
    id: "c2", category: "covenant", redLetter: false,
    ref: "Galatians 3:13-14",
    textKJV: "Christ hath redeemed us from the curse of the law, being made a curse for us... that the blessing of Abraham might come on the Gentiles through Jesus Christ.",
    textESV: "Christ redeemed us from the curse of the law by becoming a curse for us... so that in Christ Jesus the blessing of Abraham might come to the Gentiles.",
    textNKJV: "Christ has redeemed us from the curse of the law, having become a curse for us... that the blessing of Abraham might come upon the Gentiles in Christ Jesus.",
    application: "The Abrahamic blessing — which included health, wholeness, and God's favor — is yours through Christ. The Cross is the transfer of the covenant blessing to every believer.",
    source: "TSK: cross-refs Deut 27:26, Gen 12:3, Rom 4:16",
    connections: ["h1", "h2", "h7", "h9", "c1", "c3", "cross"],
    position: { x: 62, y: 10 },
  },
  {
    id: "c3", category: "covenant", redLetter: false,
    ref: "Psalm 105:8",
    textKJV: "He hath remembered his covenant for ever, the word which he commanded to a thousand generations.",
    textESV: "He remembers his covenant forever, the word that he commanded, for a thousand generations.",
    textNKJV: "He remembers His covenant forever, the word which He commanded, for a thousand generations.",
    application: "God does not forget His covenant. Every healing promise made to Abraham, to Israel, to the early church — these are still in force. He is still bound by what He said.",
    source: "TSK: cross-refs Ps 111:5, Luke 1:72, Deut 7:9",
    connections: ["c1", "c2", "c4", "h7"],
    position: { x: 48, y: 8 },
  },
  {
    id: "c4", category: "covenant", redLetter: false,
    ref: "Hebrews 13:20-21",
    textKJV: "Now the God of peace, that brought again from the dead our Lord Jesus, that great shepherd of the sheep, through the blood of the everlasting covenant, make you perfect in every good work.",
    textESV: "Now may the God of peace who brought again from the dead our Lord Jesus, the great shepherd of the sheep, by the blood of the eternal covenant, equip you with everything good.",
    textNKJV: "Now may the God of peace who brought up our Lord Jesus from the dead, that great Shepherd of the sheep, through the blood of the everlasting covenant, make you complete in every good work.",
    application: "The New Covenant is sealed with the blood of the Resurrection. The same covenant that raised Jesus from the dead equips you. Wholeness — body and soul — is within its scope.",
    source: "TSK: cross-refs Heb 9:20, Zech 9:11, 1 Pet 2:25",
    connections: ["c2", "c3", "h9", "j2", "cross"],
    position: { x: 55, y: 15 },
  },
  {
    id: "c5", category: "covenant", redLetter: false,
    ref: "Numbers 23:19",
    textKJV: "God is not a man, that he should lie; neither the son of man, that he should repent: hath he said, and shall he not do it? or hath he spoken, and shall he not make it good?",
    textESV: "God is not man, that he should lie, or a son of man, that he should change his mind. Has he said, and will he not do it? Or has he spoken, and will he not fulfill it?",
    textNKJV: "God is not a man, that He should lie, nor a son of man, that He should repent. Has He said, and will He not do? Or has He spoken, and will He not make it good?",
    application: "Every healing promise in Scripture is a statement of God's unchanging character. He cannot lie. He will not change His mind. What He said about healing — He meant.",
    source: "TSK: cross-refs 1 Sam 15:29, Titus 1:2, Heb 6:18",
    connections: ["c1", "c3", "f1", "f10", "h7"],
    position: { x: 42, y: 20 },
  },
  {
    id: "c6", category: "covenant", redLetter: false,
    ref: "2 Corinthians 1:20",
    textKJV: "For all the promises of God in him are yea, and in him Amen, unto the glory of God by us.",
    textESV: "For all the promises of God find their Yes in him. That is why it is through him that we utter our Amen to God for his glory.",
    textNKJV: "For all the promises of God in Him are Yes, and in Him Amen, to the glory of God through us.",
    application: "Every single healing promise in Scripture is YES — already ratified in Christ. When you pray for healing, you are saying 'Amen' to something God already said yes to. It is already approved.",
    source: "TSK: cross-refs 1 Cor 1:30, Gal 3:16, Eph 1:13",
    connections: ["c1", "c2", "c5", "f1", "f3", "cross"],
    position: { x: 56, y: 28 },
  },

  // ── THE WORD ──────────────────────────────────────────────────────────────────
  {
    id: "w1", category: "word", redLetter: false,
    ref: "Proverbs 4:20-22",
    textKJV: "My son, attend to my words; incline thine ear unto my sayings... For they are life unto those that find them, and health to all their flesh.",
    textESV: "My son, be attentive to my words; incline your ear to my sayings... for they are life to those who find them, and healing to all their flesh.",
    textNKJV: "My son, give attention to my words; incline your ear to my sayings... For they are life to those who find them, and health to all their flesh.",
    application: "The Word of God is literally described as medicine — 'health to all their flesh.' This is not metaphor. Dose yourself daily: read it, speak it, meditate on it. This is the prescription.",
    source: "TSK: cross-refs John 6:63, Ps 107:20, Deut 32:47",
    connections: ["f2", "f7", "w2", "h5", "h10"],
    position: { x: 57, y: 88 },
  },
  {
    id: "w2", category: "word", redLetter: false,
    ref: "Psalm 107:20",
    textKJV: "He sent his word, and healed them, and delivered them from their destructions.",
    textESV: "He sent out his word and healed them, and delivered them from their destruction.",
    textNKJV: "He sent His word and healed them, and delivered them from their destructions.",
    application: "God's primary healing instrument is His Word. This verse describes the pattern throughout Israel's history — and it is still the pattern. Release the Word; receive the healing.",
    source: "TSK: cross-refs Matt 8:8, Ps 147:15, John 4:50",
    connections: ["f2", "f7", "w1", "h10", "p3", "j1"],
    position: { x: 67, y: 93 },
  },
  {
    id: "w3", category: "word", redLetter: true,
    ref: "John 8:31-32",
    textKJV: "If ye continue in my word, then are ye my disciples indeed; and ye shall know the truth, and the truth shall make you free.",
    textESV: "If you abide in my word, you are truly my disciples, and you will know the truth, and the truth will set you free.",
    textNKJV: "If you abide in My word, you are My disciples indeed. And you shall know the truth, and the truth shall make you free.",
    application: "Freedom — including freedom from sickness — comes through abiding in the Word. It is not momentary exposure but sustained dwelling that produces the knowing that sets you free.",
    source: "TSK: cross-refs John 15:7, 1 John 2:14, Col 3:16",
    connections: ["w1", "w2", "f1", "f2", "j3"],
    position: { x: 48, y: 35 },
  },
  {
    id: "w4", category: "word", redLetter: false,
    ref: "Isaiah 55:11",
    textKJV: "So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in the thing whereto I sent it.",
    textESV: "So shall my word be that goes out from my mouth; it shall not return to me empty, but it shall accomplish that which I purpose, and shall succeed in the thing for which I sent it.",
    textNKJV: "So shall My word be that goes forth from My mouth; it shall not return to Me void, but it shall accomplish what I please, and it shall prosper in the thing for which I sent it.",
    application: "When you speak healing scriptures over yourself, that Word does not bounce back empty. It is sent on a mission. Trust the Word to accomplish what God said it would accomplish.",
    source: "TSK: cross-refs Jer 23:29, Heb 4:12, Ps 33:9",
    connections: ["w1", "w2", "w3", "h10", "c5"],
    position: { x: 58, y: 72 },
  },
  {
    id: "w5", category: "word", redLetter: false,
    ref: "Hebrews 4:12",
    textKJV: "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit.",
    textESV: "For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit.",
    textNKJV: "For the word of God is living and powerful, and sharper than any two-edged sword, piercing even to the division of soul and spirit.",
    application: "The Word is alive. It is not ancient literature — it is a living force. When you open Scripture, you are handling something that breathes and acts. It gets into the places medicine cannot reach.",
    source: "TSK: cross-refs Rev 1:16, John 6:63, 1 Thess 2:13",
    connections: ["w1", "w3", "w4", "f1", "j1"],
    position: { x: 68, y: 60 },
  },

  // ── JESUS THE HEALER ──────────────────────────────────────────────────────────
  {
    id: "j1", category: "jesus", redLetter: true,
    ref: "Luke 4:18",
    textKJV: "The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor; he hath sent me to heal the brokenhearted, to preach deliverance to the captives, and recovering of sight to the blind, to set at liberty them that are bruised.",
    textESV: "The Spirit of the Lord is upon me, because he has anointed me to proclaim good news to the poor. He has sent me to proclaim liberty to the captives and recovering of sight to the blind, to set at liberty those who are oppressed.",
    textNKJV: "The Spirit of the Lord is upon Me, because He has anointed Me to preach the gospel to the poor; He has sent Me to heal the brokenhearted, to proclaim liberty to the captives and recovery of sight to the blind, to set at liberty those who are oppressed.",
    application: "Jesus declared His own mission statement in His own words. Healing was central to why He came — not incidental, not occasional, not for a select few. This was His purpose.",
    source: "TSK: cross-refs Isa 61:1, Matt 11:5, Acts 10:38",
    connections: ["h1", "h3", "h7", "h8", "h10", "j2", "c2", "cross"],
    position: { x: 50, y: 26 },
  },
  {
    id: "j2", category: "jesus", redLetter: false,
    ref: "Hebrews 13:8",
    textKJV: "Jesus Christ the same yesterday, and to day, and for ever.",
    textESV: "Jesus Christ is the same yesterday and today and forever.",
    textNKJV: "Jesus Christ is the same yesterday, today, and forever.",
    application: "The Jesus who healed in the Gospels is the Jesus who hears your prayer today. His willingness has not changed. His power has not diminished. Your access through the Cross has not expired.",
    source: "TSK: cross-refs Mal 3:6, Rev 1:8, John 14:6",
    connections: ["f5", "j1", "j3", "h3", "h7", "c4"],
    position: { x: 62, y: 42 },
  },
  {
    id: "j3", category: "jesus", redLetter: true,
    ref: "John 10:10",
    textKJV: "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.",
    textESV: "The thief comes only to steal and kill and destroy. I came that they may have life and have it abundantly.",
    textNKJV: "The thief does not come except to steal, and to kill, and to destroy. I have come that they may have life, and that they may have it more abundantly.",
    application: "Jesus draws a clear line: sickness is the thief's work. Abundant life — whole, full, flourishing — is Christ's purpose for you. These two missions are in direct opposition. Only one wins.",
    source: "TSK: cross-refs John 8:44, 1 John 3:8, Ezek 34:2",
    connections: ["h8", "j1", "j2", "f6", "p4", "cross"],
    position: { x: 62, y: 62 },
  },
  {
    id: "j4", category: "jesus", redLetter: true,
    ref: "Matthew 8:2-3",
    textKJV: "And, behold, there came a leper and worshipped him, saying, Lord, if thou wilt, thou canst make me clean. And Jesus put forth his hand, and touched him, saying, I will; be thou clean. And immediately his leprosy was cleansed.",
    textESV: "And behold, a leper came to him and knelt before him, saying, 'Lord, if you will, you can make me clean.' And Jesus stretched out his hand and touched him, saying, 'I will; be clean.' And immediately his leprosy was cleansed.",
    textNKJV: "And behold, a leper came and worshiped Him, saying, 'Lord, if You are willing, You can make me clean.' Then Jesus put out His hand and touched him, saying, 'I am willing; be cleansed.' Immediately his leprosy was cleansed.",
    application: "The leper asked 'If you will' — Jesus answered 'I will.' This is the settled answer to the question every sick person asks. God's will for healing is not mysterious; Jesus declared it plainly.",
    source: "TSK: cross-refs Mark 1:40, Luke 5:12, Lev 14:2",
    connections: ["j1", "j2", "j3", "h3", "h8"],
    position: { x: 52, y: 44 },
  },
  {
    id: "j5", category: "jesus", redLetter: false,
    ref: "Malachi 4:2",
    textKJV: "But unto you that fear my name shall the Sun of righteousness arise with healing in his wings.",
    textESV: "But for you who fear my name, the sun of righteousness shall rise with healing in its wings.",
    textNKJV: "But to you who fear My name the Sun of Righteousness shall arise with healing in His wings.",
    application: "The Messianic promise: when Christ — the Sun of Righteousness — rises, He comes with healing embedded in His very nature. His arrival brings healing as naturally as sunrise brings light.",
    source: "TSK: cross-refs Luke 1:78, Isa 60:1, Rev 22:2",
    connections: ["j1", "j2", "h7", "c2", "cross"],
    position: { x: 65, y: 25 },
  },

  // ── THE CROSS ─────────────────────────────────────────────────────────────────
  {
    id: "cross", category: "cross", redLetter: false,
    ref: "John 19:30",
    textKJV: "When Jesus therefore had received the vinegar, he said, It is finished: and he bowed his head, and gave up the ghost.",
    textESV: "When Jesus had received the sour wine, he said, 'It is finished,' and he bowed his head and gave up his spirit.",
    textNKJV: "So when Jesus had received the sour wine, He said, 'It is finished!' And bowing His head, He gave up His spirit.",
    application: "'It is finished' — tetelestai. The Greek word means 'paid in full.' The debt of sin, the curse of the law, the right of the enemy over your body: all of it paid. Nothing remains to be earned. Only received.",
    source: "TSK: cross-refs Isa 53:5, Heb 9:12, Col 2:14",
    connections: ["h1", "h9", "c2", "c4", "c6", "j1", "j3", "j5", "f9", "f10"],
    position: { x: 50, y: 50 },
    isCross: true,
  },
];

// ── POSITIONS are embedded in each node above ─────────────────────────────────
// Connections are bidirectional — the renderer builds edges from both sides.
